### ISSUE TITLE
Add typescript

### ISSUE THREAD

**Issue by omega1996** [mkolsv/vue3-m-circle-progress-bar#1]
Thank you for such a good progress bar
Please add typescript support for your project

**Comment by mkolsv** [comment]
@omega1996 Hi!
I've added TypeScript support to the latest beta version. Could you check pls?

https://www.npmjs.com/package/vue3-m-circle-progress-bar/v/1.0.0-beta.3

Btw, The current stable version(0.5.1) should also work with TS. What issues are you have?
