### ISSUE TITLE
support reverse progress

### ISSUE THREAD

**Issue by Eliasfied** [mkolsv/vue3-m-circle-progress-bar#3]
hello,

im using your progress bar for displaying a timer that starts at for example 30 seconds and counts down to 0.
It all works good but the progress bar is obviously starting by being full and getting less every second instead of getting fuller every second because im doing a countdown instead of adding.

Would be nice to have a reverse prop or something for countdowns where you want to **number to decrease but the fill of the circle to increase over time**

thanks my friend :)

greetings eli

**Comment by mkolsv** [comment]
@Eliasfied hi!

Could you please check the latest version? (0.6.0)

I added `reversedFilling` **(Boolean)** prop. Hope it’s helpful!

**Comment by Eliasfied** [comment]
wow that was fast it works perfectly thank u very much :)
