### ISSUE TITLE
How to set the another color 

### ISSUE THREAD

**Issue by xoewrl** [mkolsv/vue3-m-circle-progress-bar#5]
the gray part of the ring

**Comment by xoewrl** [comment]
.circle-progress__line--back {
    stroke: red;
    stroke-dashoffset: 0;
}

**Comment by mkolsv** [comment]
@doglex Hey!
Yes, you can easily change the color with CSS.
I also will add additional props for this soon

**Comment by mkolsv** [comment]
@doglex This package has been deprecated.
Just install a new one in your app - https://www.npmjs.com/package/circle-progress.vue

Also, I have added new props that allow you to set a color for the back circle.
Just install a new package and use props - `colorBack`

Hope it helps!

**Comment by xoewrl** [comment]
> @doglex This package has been deprecated. Just install a new one in your app - https://www.npmjs.com/package/circle-progress.vue
> 
> Also, I have added new props that allow you to set a color for the back circle. Just install a new package and use props - `colorBack`
> 
> Hope it helps!

great
